### ISSUE TITLE
Issue with metric uppassing indexing

### ISSUE THREAD

**Issue by s0tt** [s0tt/modAL#2]
https://github.com/s0tt/modAL/blob/85530e79f8e960c1d8c490f590ca200bbf83bd08/modAL/utils/selection.py#L37

Hi @maxkeller321,
there seems to be an issue with this line, as the max_idx is not availabel in shuffled_argmax.
Can you have a look into this?

**Comment by maxkeller321** [comment]
Fixed: Commit:  20906ba9f0d685d5832d6c58fb1c4f7bca0a1c44
