### ISSUE TITLE
Error in learner.query with maximize mean strategy

### ISSUE THREAD

**Issue by s0tt** [s0tt/modAL#4]
Retrieved the following error when using maximize lean as query strategy from our bert_test:

`INFO:root:Dropout: start prediction forward pass
Traceback (most recent call last):
  File "c:/Git/ActiveLearningProject/Bert_modAL/bert_test.py", line 196, in <module>
    mean_idx, mean_instance, mean_metric = learnerMean.query(special_input_array, n_instances=4, dropout_layer_indexes=[7, 16], num_cycles=2)
  File "c:\Git\ActiveLearningProject\Bert_modAL\../modAL\modAL\models\base.py", line 176, in query
    return query_result, retrieve_rows(X_pool, query_result), query_metrics
  File "c:\Git\ActiveLearningProject\Bert_modAL\../modAL\modAL\utils\data.py", line 108, in retrieve_rows
    return X[I]
IndexError: too many indices for tensor of dimension 3`

@maxkeller321 have you experienced something like this? Seems to be a dimension problem with the retrieve rows of the query result

**Comment by maxkeller321** [comment]
The error comes from the fact that the mean_std query strategy does only work when the output tensor of the forward pass is just a vector for each instance and not a matrix as it is the case of our BERT-QA atm. 

It will work with the modified BERT-QA of Maximilian. You can check the functionality with the basic Pytorch active learner.
